version: '3'
services:
  frog:
    image: knsk96/frogrepostore:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  dog:
    image: knsk96/dogrepostore:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  cat:
    image: knsk96/catrepostore:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  ant:
    image: knsk96/antrepostore:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
