version: '3'
services:
  aws:
    image: knsk96/aws:latest
    ports:
      - "80:80"
    volume:
      - "awsvolume"
    deploy:
      replicas: 3

  devops:
    image: knsk96/devops:latest
    ports:
      - "81:80"
    volume:
      - "devopsvolume"
    deploy:
      replicas: 3

  linux:
    image: knsk96/linux:latest
    ports:
      - "82:80"
    volume:
      - "linuxvolume"
    deploy:
      replicas: 3

  azure:
    image: knsk96/azure:latest
    ports:
      - "83:80"
    volume:
      - "azurevolume"
    deploy:
      replicas: 3
