version: '3'
services:
  aws:
    image: knsk96/aws:latest
    ports:
      - "90:80"
    deploy:
      replicas: 3

  devops:
    image: knsk96/devops:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3

  linux:
    image: knsk96/linux:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3

  azure:
    image: knsk96/azure:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
